/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/character/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Character(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./public/models/character/model.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="KayKit_Animated_Character">
          <primitive object={nodes.Body} />
          <skinnedMesh name="outline" geometry={nodes.outline.geometry} material={materials.outline} skeleton={nodes.outline.skeleton} />
          <skinnedMesh name="PrototypePete" geometry={nodes.PrototypePete.geometry} material={materials.PrototypePete} skeleton={nodes.PrototypePete.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./public/models/character/model.glb')